### ISSUE TITLE
[bug] remove a nonexistent container causes panic

### ISSUE THREAD

**Issue by xlgao-zju** [hyperhq/hypercli#17]
When I remove a nonexistent container, I get a panic. The error message is shown below.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x53ffb1]

goroutine 1 [running]:
panic(0xa332a0, 0xc82000e190)
	/opt/go/src/runtime/panic.go:464 +0x3e6
encoding/json.(*Decoder).refill(0xc8203dc000, 0x0, 0x0)
	/opt/go/src/encoding/json/stream.go:152 +0x281
encoding/json.(*Decoder).readValue(0xc8203dc000, 0x1, 0x0, 0x0)
	/opt/go/src/encoding/json/stream.go:128 +0x413
encoding/json.(*Decoder).Decode(0xc8203dc000, 0x902120, 0xc82025b100, 0x0, 0x0)
	/opt/go/src/encoding/json/stream.go:57 +0x159
github.com/docker/engine-api/client.(*Client).ContainerRemove(0xc8200a6240, 0x7ffde265d190, 0x4, 0xc820000000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/xlgao/gocode/src/github.com/hyperhq/hypercli/vendor/src/github.com/docker/engine-api/client/container_remove.go:26 +0x50e
github.com/hyperhq/hypercli/api/client.(*DockerCli).removeContainer(0xc8200a61b0, 0x7ffde265d190, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/xlgao/gocode/src/github.com/hyperhq/hypercli/api/client/rm.go:55 +0xcb
github.com/hyperhq/hypercli/api/client.(*DockerCli).CmdRm(0xc8200a61b0, 0xc8200780b0, 0x1, 0x1, 0x0, 0x0)
	/home/xlgao/gocode/src/github.com/hyperhq/hypercli/api/client/rm.go:31 +0x5c4
reflect.callMethod(0xc8202c48d0, 0xc820199c28)
	/opt/go/src/reflect/value.go:631 +0x1fc
reflect.methodValueCall(0xc8200780b0, 0x1, 0x1, 0x1, 0xc8202c48d0, 0x0, 0x0, 0xc8202c48d0, 0x0, 0x468724, ...)
	/opt/go/src/reflect/asm_amd64.s:29 +0x36
github.com/hyperhq/hypercli/cli.(*Cli).Run(0xc8202c4540, 0xc8200780a0, 0x2, 0x2, 0x0, 0x0)
	/home/xlgao/gocode/src/github.com/hyperhq/hypercli/cli/cli.go:89 +0x384
main.main()
	/home/xlgao/gocode/src/github.com/hyperhq/hypercli/hyper/hyper.go:63 +0x435
```

**Comment by carmark** [comment]
@xlgao-zju Do you run the client built from the latest commit?

**Comment by xlgao-zju** [comment]
@carmark test with the latest commit, the bug gets fixed. Good job :+1:
